name: Run PR checks

on:
  push:
    branches-ignore:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: NPM Install
        run: |
          npm install

      - name: Build
        run: |
          npm run build

      - name: Unit tests
        run: |
          npm run test
